version: '3.8'
services:
  # (선택) MySQL 설정 예시
  db:
    image: mysql:8.0
    container_name: myproject-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myproject-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    # 환경변수가 필요하다면 아래 처럼 지정 가능
    # environment:
    #   - SPRING_PROFILES_ACTIVE=prod

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: myproject-ai
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myproject-frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://localhost:8080
      - AI_URL=http://localhost:8000
    depends_on:
      - backend
      - ai

volumes:
  db_data:

